# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

#Users (for demo)
User.create(username: 'Administrator', password: 'password', password_confirmation: 'password', role: 'admin', locale: 'en')
User.create(username: 'AdministratorES', password: 'password', password_confirmation: 'password', role: 'admin', locale: 'es')
User.create(username: 'Employee', password: 'password', password_confirmation: 'password', role: 'employee', locale: 'en')
User.create(username: 'Manager', password: 'password', password_confirmation: 'password', role: 'manager', locale: 'en')

#Departments (for demo)
Department.create(department_number: '1', name: 'Executive')
Department.create(department_number: '2', name: 'Human Resources')
Department.create(department_number: '3', name: 'IT')
Department.create(department_number: '4', name: 'Finance')
Department.create(department_number: '5', name: 'Marketing')
Department.create(department_number: '6', name: 'Payroll')

#Locations (for demo)
Location.create(name: 'Headquarters', address_line1: '123 Fake Street', city: "Citytown", province: 'MA', postal: '12345', country: 'US')
Location.create(name: 'Sales Office 1', address_line1: '123 Fake Street', city: "Citytown", province: 'RI', postal: '23456', country: 'US')

#Job Titles (for demo)
JobTitle.create(job_title: 'Chief Executive Officer')
JobTitle.create(job_title: 'Chief Information Officer')
JobTitle.create(job_title: 'Chief Finance Officer')
JobTitle.create(job_title: 'VP Finance')
JobTitle.create(job_title: 'HR Administrator')
JobTitle.create(job_title: 'Principle Analyst')
JobTitle.create(job_title: 'Senior Analyst')
JobTitle.create(job_title: 'Analyst')
JobTitle.create(job_title: 'Junior Analyst')
JobTitle.create(job_title: 'Principle Programmer')
JobTitle.create(job_title: 'Senior Programmer')
JobTitle.create(job_title: 'Programmer')
JobTitle.create(job_title: 'Junior Programmer')

#Pay Grades (for demo)
PayGrade.create(description: 'Grade 01', minimum: '10000', maximum: '20000', currency_code: 'USD')
PayGrade.create(description: 'Grade 02', minimum: '20000', maximum: '30000', currency_code: 'USD')
PayGrade.create(description: 'Grade 03', minimum: '30000', maximum: '40000', currency_code: 'USD')
PayGrade.create(description: 'Grade 04', minimum: '40000', maximum: '50000', currency_code: 'USD')
PayGrade.create(description: 'Grade 05', minimum: '50000', maximum: '60000', currency_code: 'USD')
PayGrade.create(description: 'Grade 06', minimum: '60000', maximum: '70000', currency_code: 'USD')

#Languages
Language.create(language_description: 'English')
Language.create(language_description: 'Spanish')
Language.create(language_description: 'French')
Language.create(language_description: 'Italian')
Language.create(language_description: 'Mandarin')
Language.create(language_description: 'Hindi')
Language.create(language_description: 'Arabic')
Language.create(language_description: 'Portuguese')
Language.create(language_description: 'Bengali')
Language.create(language_description: 'Russian')
Language.create(language_description: 'Japanese')
Language.create(language_description: 'German')
Language.create(language_description: 'Vietnamese')
Language.create(language_description: 'Dutch')
Language.create(language_description: 'Polish')
Language.create(language_description: 'Swedish')
Language.create(language_description: 'Danish')
Language.create(language_description: 'Norwegian')
Language.create(language_description: 'Turkish')

#Education Levels
EducationLevel.create(education_level_description: 'GED')
EducationLevel.create(education_level_description: 'High School Diploma')
EducationLevel.create(education_level_description: 'Associate\'s Degree')
EducationLevel.create(education_level_description: 'Bachelor\'s Degree')
EducationLevel.create(education_level_description: 'Master\'s Degree')
EducationLevel.create(education_level_description: 'PHD/Doctorate')

#Termination Reasons
TerminationReason.create(description: 'Deseased')
TerminationReason.create(description: 'Retired')
TerminationReason.create(description: 'Result of Layoff')
TerminationReason.create(description: 'Resigned - At Request of Employee')
TerminationReason.create(description: 'Resigned - At Request of Company')
TerminationReason.create(description: 'Other')

#Relationships
Relationship.create(description: 'Parent')
Relationship.create(description: 'Spouse')
Relationship.create(description: 'Child')
Relationship.create(description: 'Domestic Partner')
Relationship.create(description: 'Adopted Child')
Relationship.create(description: 'Sibling')
Relationship.create(description: 'Grandparent')
Relationship.create(description: 'Friend')
Relationship.create(description: 'Other')

#Countries
Country.create(country_code: 'AF', description: 'Afghanistan')
Country.create(country_code: 'AX', description: 'Åland Islands')
Country.create(country_code: 'AL', description: 'Albania')
Country.create(country_code: 'DZ', description: 'Algeria')
Country.create(country_code: 'AS', description: 'American Samoa')
Country.create(country_code: 'AD', description: 'Andorra')
Country.create(country_code: 'AO', description: 'Angola')
Country.create(country_code: 'AI', description: 'Anguilla')
Country.create(country_code: 'AQ', description: 'Antarctica')
Country.create(country_code: 'AG', description: 'Antigua and Barbuda')
Country.create(country_code: 'AR', description: 'Argentina')
Country.create(country_code: 'AM', description: 'Armenia')
Country.create(country_code: 'AW', description: 'Aruba')
Country.create(country_code: 'AU', description: 'Australia')
Country.create(country_code: 'AT', description: 'Austria')
Country.create(country_code: 'AZ', description: 'Azerbaijan')
Country.create(country_code: 'BS', description: 'Bahamas')
Country.create(country_code: 'BH', description: 'Bahrain')
Country.create(country_code: 'BD', description: 'Bangladesh')
Country.create(country_code: 'BB', description: 'Barbados')
Country.create(country_code: 'BY', description: 'Belarus')
Country.create(country_code: 'BE', description: 'Belgium')
Country.create(country_code: 'BZ', description: 'Belize')
Country.create(country_code: 'BJ', description: 'Benin')
Country.create(country_code: 'BM', description: 'Bermuda')
Country.create(country_code: 'BT', description: 'Bhutan')
Country.create(country_code: 'BO', description: 'Bolivia, Plurinational State of')
Country.create(country_code: 'BQ', description: 'Bonaire, Sint Eustatius and Saba')
Country.create(country_code: 'BA', description: 'Bosnia and Herzegovina')
Country.create(country_code: 'BW', description: 'Botswana')
Country.create(country_code: 'BV', description: 'Bouvet Island')
Country.create(country_code: 'BR', description: 'Brazil')
Country.create(country_code: 'IO', description: 'British Indian Ocean Territory')
Country.create(country_code: 'BN', description: 'Brunei Darussalam')
Country.create(country_code: 'BG', description: 'Bulgaria')
Country.create(country_code: 'BF', description: 'Burkina Faso')
Country.create(country_code: 'BI', description: 'Burundi')
Country.create(country_code: 'KH', description: 'Cambodia')
Country.create(country_code: 'CM', description: 'Cameroon')
Country.create(country_code: 'CA', description: 'Canada')
Country.create(country_code: 'CV', description: 'Cape Verde')
Country.create(country_code: 'KY', description: 'Cayman Islands')
Country.create(country_code: 'CF', description: 'Central African Republic')
Country.create(country_code: 'TD', description: 'Chad')
Country.create(country_code: 'CL', description: 'Chile')
Country.create(country_code: 'CN', description: 'China')
Country.create(country_code: 'CX', description: 'Christmas Island')
Country.create(country_code: 'CC', description: 'Cocos (Keeling) Islands')
Country.create(country_code: 'CO', description: 'Colombia')
Country.create(country_code: 'KM', description: 'Comoros')
Country.create(country_code: 'CG', description: 'Congo')
Country.create(country_code: 'CD', description: 'Congo, the Democratic Republic of the')
Country.create(country_code: 'CK', description: 'Cook Islands')
Country.create(country_code: 'CR', description: 'Costa Rica')
Country.create(country_code: 'CI', description: 'Côte d\'Ivoire')
Country.create(country_code: 'HR', description: 'Croatia')
Country.create(country_code: 'CU', description: 'Cuba')
Country.create(country_code: 'CW', description: 'Curaçao')
Country.create(country_code: 'CY', description: 'Cyprus')
Country.create(country_code: 'CZ', description: 'Czech Republic')
Country.create(country_code: 'DK', description: 'Denmark')
Country.create(country_code: 'DJ', description: 'Djibouti')
Country.create(country_code: 'DM', description: 'Dominica')
Country.create(country_code: 'DO', description: 'Dominican Republic')
Country.create(country_code: 'EC', description: 'Ecuador')
Country.create(country_code: 'EG', description: 'Egypt')
Country.create(country_code: 'SV', description: 'El Salvador')
Country.create(country_code: 'GQ', description: 'Equatorial Guinea')
Country.create(country_code: 'ER', description: 'Eritrea')
Country.create(country_code: 'EE', description: 'Estonia')
Country.create(country_code: 'ET', description: 'Ethiopia')
Country.create(country_code: 'FK', description: 'Falkland Islands (Malvinas)')
Country.create(country_code: 'FO', description: 'Faroe Islands')
Country.create(country_code: 'FJ', description: 'Fiji')
Country.create(country_code: 'FI', description: 'Finland')
Country.create(country_code: 'FR', description: 'France')
Country.create(country_code: 'GF', description: 'French Guiana')
Country.create(country_code: 'PF', description: 'French Polynesia')
Country.create(country_code: 'TF', description: 'French Southern Territories')
Country.create(country_code: 'GA', description: 'Gabon')
Country.create(country_code: 'GM', description: 'Gambia')
Country.create(country_code: 'GE', description: 'Georgia')
Country.create(country_code: 'DE', description: 'Germany')
Country.create(country_code: 'GH', description: 'Ghana')
Country.create(country_code: 'GI', description: 'Gibraltar')
Country.create(country_code: 'GR', description: 'Greece')
Country.create(country_code: 'GL', description: 'Greenland')
Country.create(country_code: 'GD', description: 'Grenada')
Country.create(country_code: 'GP', description: 'Guadeloupe')
Country.create(country_code: 'GU', description: 'Guam')
Country.create(country_code: 'GT', description: 'Guatemala')
Country.create(country_code: 'GG', description: 'Guernsey')
Country.create(country_code: 'GN', description: 'Guinea')
Country.create(country_code: 'GW', description: 'Guinea-Bissau')
Country.create(country_code: 'GY', description: 'Guyana')
Country.create(country_code: 'HT', description: 'Haiti')
Country.create(country_code: 'HM', description: 'Heard Island and McDonald Islands')
Country.create(country_code: 'VA', description: 'Holy See (Vatican City State)')
Country.create(country_code: 'HN', description: 'Honduras')
Country.create(country_code: 'HK', description: 'Hong Kong')
Country.create(country_code: 'HU', description: 'Hungary')
Country.create(country_code: 'IS', description: 'Iceland')
Country.create(country_code: 'IN', description: 'India')
Country.create(country_code: 'ID', description: 'Indonesia')
Country.create(country_code: 'IR', description: 'Iran, Islamic Republic of')
Country.create(country_code: 'IQ', description: 'Iraq')
Country.create(country_code: 'IE', description: 'Ireland')
Country.create(country_code: 'IM', description: 'Isle of Man')
Country.create(country_code: 'IL', description: 'Israel')
Country.create(country_code: 'IT', description: 'Italy')
Country.create(country_code: 'JM', description: 'Jamaica')
Country.create(country_code: 'JP', description: 'Japan')
Country.create(country_code: 'JE', description: 'Jersey')
Country.create(country_code: 'JO', description: 'Jordan')
Country.create(country_code: 'KZ', description: 'Kazakhstan')
Country.create(country_code: 'KE', description: 'Kenya')
Country.create(country_code: 'KI', description: 'Kiribati')
Country.create(country_code: 'KP', description: 'Korea, Democratic People\'s Republic of')
Country.create(country_code: 'KR', description: 'Korea, Republic of')
Country.create(country_code: 'KW', description: 'Kuwait')
Country.create(country_code: 'KG', description: 'Kyrgyzstan')
Country.create(country_code: 'LA', description: 'Lao People\'s Democratic Republic')
Country.create(country_code: 'LV', description: 'Latvia')
Country.create(country_code: 'LB', description: 'Lebanon')
Country.create(country_code: 'LS', description: 'Lesotho')
Country.create(country_code: 'LR', description: 'Liberia')
Country.create(country_code: 'LY', description: 'Libya')
Country.create(country_code: 'LI', description: 'Liechtenstein')
Country.create(country_code: 'LT', description: 'Lithuania')
Country.create(country_code: 'LU', description: 'Luxembourg')
Country.create(country_code: 'MO', description: 'Macao')
Country.create(country_code: 'MK', description: 'Macedonia, the Former Yugoslav Republic of')
Country.create(country_code: 'MG', description: 'Madagascar')
Country.create(country_code: 'MW', description: 'Malawi')
Country.create(country_code: 'MY', description: 'Malaysia')
Country.create(country_code: 'MV', description: 'Maldives')
Country.create(country_code: 'ML', description: 'Mali')
Country.create(country_code: 'MT', description: 'Malta')
Country.create(country_code: 'MH', description: 'Marshall Islands')
Country.create(country_code: 'MQ', description: 'Martinique')
Country.create(country_code: 'MR', description: 'Mauritania')
Country.create(country_code: 'MU', description: 'Mauritius')
Country.create(country_code: 'YT', description: 'Mayotte')
Country.create(country_code: 'MX', description: 'Mexico')
Country.create(country_code: 'FM', description: 'Micronesia, Federated States of')
Country.create(country_code: 'MD', description: 'Moldova, Republic of')
Country.create(country_code: 'MC', description: 'Monaco')
Country.create(country_code: 'MN', description: 'Mongolia')
Country.create(country_code: 'ME', description: 'Montenegro')
Country.create(country_code: 'MS', description: 'Montserrat')
Country.create(country_code: 'MA', description: 'Morocco')
Country.create(country_code: 'MZ', description: 'Mozambique')
Country.create(country_code: 'MM', description: 'Myanmar')
Country.create(country_code: 'NA', description: 'Namibia')
Country.create(country_code: 'NR', description: 'Nauru')
Country.create(country_code: 'NP', description: 'Nepal')
Country.create(country_code: 'NL', description: 'Netherlands')
Country.create(country_code: 'NC', description: 'New Caledonia')
Country.create(country_code: 'NZ', description: 'New Zealand')
Country.create(country_code: 'NI', description: 'Nicaragua')
Country.create(country_code: 'NE', description: 'Niger')
Country.create(country_code: 'NG', description: 'Nigeria')
Country.create(country_code: 'NU', description: 'Niue')
Country.create(country_code: 'NF', description: 'Norfolk Island')
Country.create(country_code: 'MP', description: 'Northern Mariana Islands')
Country.create(country_code: 'NO', description: 'Norway')
Country.create(country_code: 'OM', description: 'Oman')
Country.create(country_code: 'PK', description: 'Pakistan')
Country.create(country_code: 'PW', description: 'Palau')
Country.create(country_code: 'PS', description: 'Palestine, State of')
Country.create(country_code: 'PA', description: 'Panama')
Country.create(country_code: 'PG', description: 'Papua New Guinea')
Country.create(country_code: 'PY', description: 'Paraguay')
Country.create(country_code: 'PE', description: 'Peru')
Country.create(country_code: 'PH', description: 'Philippines')
Country.create(country_code: 'PN', description: 'Pitcairn')
Country.create(country_code: 'PL', description: 'Poland')
Country.create(country_code: 'PT', description: 'Portugal')
Country.create(country_code: 'PR', description: 'Puerto Rico')
Country.create(country_code: 'QA', description: 'Qatar')
Country.create(country_code: 'RE', description: 'Réunion')
Country.create(country_code: 'RO', description: 'Romania')
Country.create(country_code: 'RU', description: 'Russian Federation')
Country.create(country_code: 'RW', description: 'Rwanda')
Country.create(country_code: 'BL', description: 'Saint Barthélemy')
Country.create(country_code: 'SH', description: 'Saint Helena, Ascension and Tristan da Cunha')
Country.create(country_code: 'KN', description: 'Saint Kitts and Nevis')
Country.create(country_code: 'LC', description: 'Saint Lucia')
Country.create(country_code: 'MF', description: 'Saint Martin (French part)')
Country.create(country_code: 'PM', description: 'Saint Pierre and Miquelon')
Country.create(country_code: 'VC', description: 'Saint Vincent and the Grenadines')
Country.create(country_code: 'WS', description: 'Samoa')
Country.create(country_code: 'SM', description: 'San Marino')
Country.create(country_code: 'ST', description: 'Sao Tome and Principe')
Country.create(country_code: 'SA', description: 'Saudi Arabia')
Country.create(country_code: 'SN', description: 'Senegal')
Country.create(country_code: 'RS', description: 'Serbia')
Country.create(country_code: 'SC', description: 'Seychelles')
Country.create(country_code: 'SL', description: 'Sierra Leone')
Country.create(country_code: 'SG', description: 'Singapore')
Country.create(country_code: 'SX', description: 'Sint Maarten (Dutch part)')
Country.create(country_code: 'SK', description: 'Slovakia')
Country.create(country_code: 'SI', description: 'Slovenia')
Country.create(country_code: 'SB', description: 'Solomon Islands')
Country.create(country_code: 'SO', description: 'Somalia')
Country.create(country_code: 'ZA', description: 'South Africa')
Country.create(country_code: 'GS', description: 'South Georgia and the South Sandwich Islands')
Country.create(country_code: 'SS', description: 'South Sudan')
Country.create(country_code: 'ES', description: 'Spain')
Country.create(country_code: 'LK', description: 'Sri Lanka')
Country.create(country_code: 'SD', description: 'Sudan')
Country.create(country_code: 'SR', description: 'Suriname')
Country.create(country_code: 'SJ', description: 'Svalbard and Jan Mayen')
Country.create(country_code: 'SZ', description: 'Swaziland')
Country.create(country_code: 'SE', description: 'Sweden')
Country.create(country_code: 'CH', description: 'Switzerland')
Country.create(country_code: 'SY', description: 'Syrian Arab Republic')
Country.create(country_code: 'TW', description: 'Taiwan, Province of China')
Country.create(country_code: 'TJ', description: 'Tajikistan')
Country.create(country_code: 'TZ', description: 'Tanzania, United Republic of')
Country.create(country_code: 'TH', description: 'Thailand')
Country.create(country_code: 'TL', description: 'Timor-Leste')
Country.create(country_code: 'TG', description: 'Togo')
Country.create(country_code: 'TK', description: 'Tokelau')
Country.create(country_code: 'TO', description: 'Tonga')
Country.create(country_code: 'TT', description: 'Trinidad and Tobago')
Country.create(country_code: 'TN', description: 'Tunisia')
Country.create(country_code: 'TR', description: 'Turkey')
Country.create(country_code: 'TM', description: 'Turkmenistan')
Country.create(country_code: 'TC', description: 'Turks and Caicos Islands')
Country.create(country_code: 'TV', description: 'Tuvalu')
Country.create(country_code: 'UG', description: 'Uganda')
Country.create(country_code: 'UA', description: 'Ukraine')
Country.create(country_code: 'AE', description: 'United Arab Emirates')
Country.create(country_code: 'GB', description: 'United Kingdom')
Country.create(country_code: 'US', description: 'United States')
Country.create(country_code: 'UM', description: 'United States Minor Outlying Islands')
Country.create(country_code: 'UY', description: 'Uruguay')
Country.create(country_code: 'UZ', description: 'Uzbekistan')
Country.create(country_code: 'VU', description: 'Vanuatu')
Country.create(country_code: 'VE', description: 'Venezuela, Bolivarian Republic of')
Country.create(country_code: 'VN', description: 'Viet Nam')
Country.create(country_code: 'VG', description: 'Virgin Islands, British')
Country.create(country_code: 'VI', description: 'Virgin Islands, U.S.')
Country.create(country_code: 'WF', description: 'Wallis and Futuna')
Country.create(country_code: 'EH', description: 'Western Sahara')
Country.create(country_code: 'YE', description: 'Yemen')
Country.create(country_code: 'ZM', description: 'Zambia')
Country.create(country_code: 'ZW', description: 'Zimbabwe')


#States - United States of America
State.create(country_id: '236', state_code: 'AL', description: 'Alabama')
State.create(country_id: '236', state_code: 'AZ', description: 'Arizona')
State.create(country_id: '236', state_code: 'AR', description: 'Arkansas')
State.create(country_id: '236', state_code: 'CA', description: 'California')
State.create(country_id: '236', state_code: 'CO', description: 'Colorado')
State.create(country_id: '236', state_code: 'CT', description: 'Connecticut')
State.create(country_id: '236', state_code: 'DE', description: 'Deleware')
State.create(country_id: '236', state_code: 'FL', description: 'Florida')
State.create(country_id: '236', state_code: 'GA', description: 'Georgia')
State.create(country_id: '236', state_code: 'HI', description: 'Hawaii')
State.create(country_id: '236', state_code: 'ID', description: 'Idaho')
State.create(country_id: '236', state_code: 'IL', description: 'Illinois')
State.create(country_id: '236', state_code: 'IN', description: 'Indiana')
State.create(country_id: '236', state_code: 'IA', description: 'Iowa')
State.create(country_id: '236', state_code: 'KS', description: 'Kansas')
State.create(country_id: '236', state_code: 'KY', description: 'Kentucky')
State.create(country_id: '236', state_code: 'LA', description: 'Louisiana')
State.create(country_id: '236', state_code: 'ME', description: 'Maine')
State.create(country_id: '236', state_code: 'MD', description: 'Maryland')
State.create(country_id: '236', state_code: 'MA', description: 'Massachussetts')
State.create(country_id: '236', state_code: 'MI', description: 'Michigan')
State.create(country_id: '236', state_code: 'MN', description: 'Minnesota')
State.create(country_id: '236', state_code: 'MS', description: 'Mississippi')
State.create(country_id: '236', state_code: 'MO', description: 'Missouri')
State.create(country_id: '236', state_code: 'MT', description: 'ontana')
State.create(country_id: '236', state_code: 'NE', description: 'Nebraska')
State.create(country_id: '236', state_code: 'NV', description: 'Nevada')
State.create(country_id: '236', state_code: 'NH', description: 'New Hampshire')
State.create(country_id: '236', state_code: 'NJ', description: 'New Jersey')
State.create(country_id: '236', state_code: 'NM', description: 'New Mexico')
State.create(country_id: '236', state_code: 'NY', description: 'New York')
State.create(country_id: '236', state_code: 'NC', description: 'North Carolina')
State.create(country_id: '236', state_code: 'ND', description: 'North Dakota')
State.create(country_id: '236', state_code: 'OH', description: 'Ohio')
State.create(country_id: '236', state_code: 'OK', description: 'Oklahoma')
State.create(country_id: '236', state_code: 'OR', description: 'Oregon')
State.create(country_id: '236', state_code: 'PA', description: 'Pennsylvania')
State.create(country_id: '236', state_code: 'RI', description: 'Rhode Island')
State.create(country_id: '236', state_code: 'SC', description: 'South Carolina')
State.create(country_id: '236', state_code: 'SD', description: 'South Dakota')
State.create(country_id: '236', state_code: 'TN', description: 'Tennessee')
State.create(country_id: '236', state_code: 'TX', description: 'Texas')
State.create(country_id: '236', state_code: 'UT', description: 'Utah')
State.create(country_id: '236', state_code: 'VT', description: 'Vermonth')
State.create(country_id: '236', state_code: 'VA', description: 'Virginia')
State.create(country_id: '236', state_code: 'WA', description: 'Washington')
State.create(country_id: '236', state_code: 'WV', description: 'West Virginia')
State.create(country_id: '236', state_code: 'WI', description: 'Wisconsin')
State.create(country_id: '236', state_code: 'WY', description: 'Wyoming')

#States - Canada
State.create(country_id: '40', state_code: 'AB', description: 'Alberta')
State.create(country_id: '40', state_code: 'BC', description: 'British Columbia')
State.create(country_id: '40', state_code: 'MB', description: 'Manitoba')
State.create(country_id: '40', state_code: 'NB', description: 'New Brunswick')
State.create(country_id: '40', state_code: 'NL', description: 'Newfoundland and Labrador')
State.create(country_id: '40', state_code: 'NS', description: 'Nova Scotia')
State.create(country_id: '40', state_code: 'ON', description: 'Ontario')
State.create(country_id: '40', state_code: 'PE', description: 'Prince Edward Island')
State.create(country_id: '40', state_code: 'QC', description: 'Quebec')
State.create(country_id: '40', state_code: 'SK', description: 'Saskatchewan')

#States - Netherlands
State.create(country_id: '157', state_code: 'DR', description: 'Drenthe')
State.create(country_id: '157', state_code: 'FL', description: 'Flevoland')
State.create(country_id: '157', state_code: 'FR', description: 'Friesland')
State.create(country_id: '157', state_code: 'GE', description: 'Gelderland')
State.create(country_id: '157', state_code: 'GR', description: 'Groningen')
State.create(country_id: '157', state_code: 'LI', description: 'Limburg')
State.create(country_id: '157', state_code: 'NB', description: 'North Brabant')
State.create(country_id: '157', state_code: 'NH', description: 'North Holland')
State.create(country_id: '157', state_code: 'OV', description: 'Overijssel')
State.create(country_id: '157', state_code: 'UT', description: 'Utrecht')
State.create(country_id: '157', state_code: 'ZE', description: 'Zeeland')
State.create(country_id: '157', state_code: 'ZH', description: 'South Holland')

#States - Germany
State.create(country_id: '83', state_code: 'BW', description: 'Baden-Württemberg')
State.create(country_id: '83', state_code: 'BY', description: 'Bavaria')
State.create(country_id: '83', state_code: 'BE', description: 'Berlin')
State.create(country_id: '83', state_code: 'BB', description: 'Brandenburg')
State.create(country_id: '83', state_code: 'HB', description: 'Bremen')
State.create(country_id: '83', state_code: 'HH', description: 'Hamburg')
State.create(country_id: '83', state_code: 'HE', description: 'Hesse')
State.create(country_id: '83', state_code: 'NI', description: 'Lower Saxony')
State.create(country_id: '83', state_code: 'MV', description: 'Mecklenburg-Vorpommern')
State.create(country_id: '83', state_code: 'NW', description: 'North Rhine-Westphalia')
State.create(country_id: '83', state_code: 'RP', description: 'Rhineland-Palatinate')
State.create(country_id: '83', state_code: 'SL', description: 'Saarland')
State.create(country_id: '83', state_code: 'SN', description: 'Saxony')
State.create(country_id: '83', state_code: 'ST', description: 'Saxony-Anhalt')
State.create(country_id: '83', state_code: 'SH', description: 'Schleswig-Holstein')
State.create(country_id: '83', state_code: 'TH', description: 'Thuringia')

#System Languages/Locales
SystemLanguage.create(language_code: 'af', language_description: 'Afrikaans')
SystemLanguage.create(language_code: 'ar', language_description: 'Arabic')
SystemLanguage.create(language_code: 'az', language_description: 'Azeri')
SystemLanguage.create(language_code: 'bg', language_description: 'Bulgarian')
SystemLanguage.create(language_code: 'bn', language_description: 'Bengali')
SystemLanguage.create(language_code: 'bs', language_description: 'Bosnian')
SystemLanguage.create(language_code: 'ca', language_description: 'Catalan')
SystemLanguage.create(language_code: 'cs', language_description: 'Czech')
SystemLanguage.create(language_code: 'cy', language_description: 'Welch')
SystemLanguage.create(language_code: 'da', language_description: 'Danish')
SystemLanguage.create(language_code: 'de', language_description: 'German')
SystemLanguage.create(language_code: 'de-AT', language_description: 'German (Austria)')
SystemLanguage.create(language_code: 'de-CH', language_description: 'German (Switzerland)')
SystemLanguage.create(language_code: 'el', language_description: 'Greek')
SystemLanguage.create(language_code: 'en', language_description: 'English')
SystemLanguage.create(language_code: 'en-AU', language_description: 'English (Austalia)')
SystemLanguage.create(language_code: 'en-CA', language_description: 'English (Canada)')
SystemLanguage.create(language_code: 'en-GB', language_description: 'English (Great Britain)')
SystemLanguage.create(language_code: 'en-IE', language_description: 'English (Ireland)')
SystemLanguage.create(language_code: 'en-IN', language_description: 'English (India)')
SystemLanguage.create(language_code: 'en-NZ', language_description: 'English (New Zealand)')
SystemLanguage.create(language_code: 'en-US', language_description: 'English (US)')
SystemLanguage.create(language_code: 'en-ZA', language_description: 'English (South Africa)')
SystemLanguage.create(language_code: 'eo', language_description: 'Esperanto')
SystemLanguage.create(language_code: 'es', language_description: 'Spanish')
SystemLanguage.create(language_code: 'es-419', language_description: 'Spanish (Latin America)')
SystemLanguage.create(language_code: 'es-AR', language_description: 'Spanish (Argentina)')
SystemLanguage.create(language_code: 'es-CL', language_description: 'Spanish (Chile)')
SystemLanguage.create(language_code: 'es-CO', language_description: 'Spanish (Columbia)')
SystemLanguage.create(language_code: 'es-CR', language_description: 'Spanish (Costa Rica)')
SystemLanguage.create(language_code: 'es-EC', language_description: 'Spanish (Ecuator)')
SystemLanguage.create(language_code: 'es-MX', language_description: 'Spanish (Mexico)')
SystemLanguage.create(language_code: 'es-PA', language_description: 'Spanish (Panama)')
SystemLanguage.create(language_code: 'es-PE', language_description: 'Spanish (Peru)')
SystemLanguage.create(language_code: 'es-US', language_description: 'Spanish (United States)')
SystemLanguage.create(language_code: 'es-VE', language_description: 'Spanish (Venezuela)')
SystemLanguage.create(language_code: 'et', language_description: 'Estonian')
SystemLanguage.create(language_code: 'eu', language_description: 'Basque')
SystemLanguage.create(language_code: 'fa', language_description: 'Farsi')
SystemLanguage.create(language_code: 'fi', language_description: 'Finnish')
SystemLanguage.create(language_code: 'fr', language_description: 'French')
SystemLanguage.create(language_code: 'fr-CA', language_description: 'French (Canada)')
SystemLanguage.create(language_code: 'fr-CH', language_description: 'French (Switzerland)')
SystemLanguage.create(language_code: 'gl', language_description: 'Galician')
SystemLanguage.create(language_code: 'he', language_description: 'Hebrew')
SystemLanguage.create(language_code: 'hi', language_description: 'Hindi')
SystemLanguage.create(language_code: 'hi-IN', language_description: 'Hindi (India')
SystemLanguage.create(language_code: 'hr', language_description: 'Croatian')
SystemLanguage.create(language_code: 'hu', language_description: 'Hungarian')
SystemLanguage.create(language_code: 'id', language_description: 'Indonesian')
SystemLanguage.create(language_code: 'is', language_description: 'Icelandic')
SystemLanguage.create(language_code: 'it', language_description: 'Italian')
SystemLanguage.create(language_code: 'it-CH', language_description: 'Italian (Switzerland)')
SystemLanguage.create(language_code: 'ja', language_description: 'Japanese')
SystemLanguage.create(language_code: 'km', language_description: 'Khmer')
SystemLanguage.create(language_code: 'kn', language_description: 'Kannada')
SystemLanguage.create(language_code: 'ko', language_description: 'Korean')
SystemLanguage.create(language_code: 'lo', language_description: 'Lao')
SystemLanguage.create(language_code: 'lt', language_description: 'Lithuanian')
SystemLanguage.create(language_code: 'lv', language_description: 'Latvian')
SystemLanguage.create(language_code: 'mk', language_description: 'Macedonian')
SystemLanguage.create(language_code: 'mn', language_description: 'Mongolian')
SystemLanguage.create(language_code: 'mr-IN', language_description: 'Marathi (India)')
SystemLanguage.create(language_code: 'ms', language_description: 'Malay')
SystemLanguage.create(language_code: 'nb', language_description: 'Norwegian')
SystemLanguage.create(language_code: 'ne', language_description: 'Nepali')
SystemLanguage.create(language_code: 'nl', language_description: 'Dutch')
SystemLanguage.create(language_code: 'nn', language_description: 'Norwegian')
SystemLanguage.create(language_code: 'or', language_description: 'Oryia')
SystemLanguage.create(language_code: 'pl', language_description: 'Polish')
SystemLanguage.create(language_code: 'pt', language_description: 'Portuguese (Portugal)')
SystemLanguage.create(language_code: 'pt-BR', language_description: 'Portuguese (Brazil)')
SystemLanguage.create(language_code: 'rm', language_description: 'Raeto (Romance)')
SystemLanguage.create(language_code: 'ro', language_description: 'Romanian')
SystemLanguage.create(language_code: 'ru', language_description: 'Russian')
SystemLanguage.create(language_code: 'sk', language_description: 'Slovak')
SystemLanguage.create(language_code: 'sl', language_description: 'Slovanian')
SystemLanguage.create(language_code: 'sr', language_description: 'Serbian')
SystemLanguage.create(language_code: 'sv', language_description: 'Swedish')
SystemLanguage.create(language_code: 'sw', language_description: 'Swahili')
SystemLanguage.create(language_code: 'ta', language_description: 'Tamil')
SystemLanguage.create(language_code: 'th', language_description: 'Thai')
SystemLanguage.create(language_code: 'tl', language_description: 'Tagalog')
SystemLanguage.create(language_code: 'tr', language_description: 'Turkish')
SystemLanguage.create(language_code: 'tt', language_description: 'Tatar')
SystemLanguage.create(language_code: 'uk', language_description: 'Ukranian')
SystemLanguage.create(language_code: 'ug', language_description: 'Uighur')
SystemLanguage.create(language_code: 'ur', language_description: 'Urdu')
SystemLanguage.create(language_code: 'uz', language_description: 'Uzbek')
SystemLanguage.create(language_code: 'vi', language_description: 'Vietnamese')
SystemLanguage.create(language_code: 'wo', language_description: 'Wolof')
SystemLanguage.create(language_code: 'zh-CN', language_description: 'Chinese (Simplified)')
SystemLanguage.create(language_code: 'zh-HK', language_description: 'Chinese (Hong Kong)')
SystemLanguage.create(language_code: 'zh-TW', language_description: 'Chinese (Traditional)')
SystemLanguage.create(language_code: 'zh-YUE', language_description: 'Chinese (Yue)')

#Currency Codes
Currency.create(currency_code: 'AED', description: 'United Arab Emirates Dirham')
Currency.create(currency_code: 'AFN', description: 'Afghanistan Afghani')
Currency.create(currency_code: 'ALL', description: 'Albania Lek')
Currency.create(currency_code: 'AMD', description: 'Armenia Dram')
Currency.create(currency_code: 'ANG', description: 'Netherlands Antilles Guilder')
Currency.create(currency_code: 'AOA', description: 'Angola Kwanza')
Currency.create(currency_code: 'ARS', description: 'Argentina Peso')
Currency.create(currency_code: 'AUD', description: 'Australia Dollar')
Currency.create(currency_code: 'AWG', description: 'Aruba Guilder')
Currency.create(currency_code: 'AZN', description: 'Azerbaijan New Manat')
Currency.create(currency_code: 'BAM', description: 'Bosnia and Herzegovina Convertible Marka')
Currency.create(currency_code: 'BBD', description: 'Barbados Dollar')
Currency.create(currency_code: 'BDT', description: 'Bangladesh Taka')
Currency.create(currency_code: 'BGN', description: 'Bulgaria Lev')
Currency.create(currency_code: 'BHD', description: 'Bahrain Dinar')
Currency.create(currency_code: 'BIF', description: 'Burundi Franc')
Currency.create(currency_code: 'BMD', description: 'Bermuda Dollar')
Currency.create(currency_code: 'BND', description: 'Brunei Darussalam Dollar')
Currency.create(currency_code: 'BOB', description: 'Bolivia Boliviano')
Currency.create(currency_code: 'BRL', description: 'Brazil Real')
Currency.create(currency_code: 'BSD', description: 'Bahamas Dollar')
Currency.create(currency_code: 'BTN', description: 'Bhutan Ngultrum')
Currency.create(currency_code: 'BWP', description: 'Botswana Pula')
Currency.create(currency_code: 'BYR', description: 'Belarus Ruble')
Currency.create(currency_code: 'BZD', description: 'Belize Dollar')
Currency.create(currency_code: 'CAD', description: 'Canada Dollar')
Currency.create(currency_code: 'CDF', description: 'Congo/Kinshasa Franc')
Currency.create(currency_code: 'CHF', description: 'Switzerland Franc')
Currency.create(currency_code: 'CLP', description: 'Chile Peso')
Currency.create(currency_code: 'CNY', description: 'China Yuan Renminbi')
Currency.create(currency_code: 'COP', description: 'Colombia Peso')
Currency.create(currency_code: 'CRC', description: 'Costa Rica Colon')
Currency.create(currency_code: 'CUC', description: 'Cuba Convertible Peso')
Currency.create(currency_code: 'CUP', description: 'Cuba Peso')
Currency.create(currency_code: 'CVE', description: 'Cape Verde Escudo')
Currency.create(currency_code: 'CZK', description: 'Czech Republic Koruna')
Currency.create(currency_code: 'DJF', description: 'Djibouti Franc')
Currency.create(currency_code: 'DKK', description: 'Denmark Krone')
Currency.create(currency_code: 'DOP', description: 'Dominican Republic Peso')
Currency.create(currency_code: 'DZD', description: 'Algeria Dinar')
Currency.create(currency_code: 'EGP', description: 'Egypt Pound')
Currency.create(currency_code: 'ERN', description: 'Eritrea Nakfa')
Currency.create(currency_code: 'ETB', description: 'Ethiopia Birr')
Currency.create(currency_code: 'EUR', description: 'Euro')
Currency.create(currency_code: 'FJD', description: 'Fiji Dollar')
Currency.create(currency_code: 'FKP', description: 'Falkland Islands (Malvinas) Pound')
Currency.create(currency_code: 'GBP', description: 'United Kingdom Pound')
Currency.create(currency_code: 'GEL', description: 'Georgia Lari')
Currency.create(currency_code: 'GGP', description: 'Guernsey Pound')
Currency.create(currency_code: 'GHS', description: 'Ghana Cedi')
Currency.create(currency_code: 'GIP', description: 'Gibraltar Pound')
Currency.create(currency_code: 'GMD', description: 'Gambia Dalasi')
Currency.create(currency_code: 'GNF', description: 'Guinea Franc')
Currency.create(currency_code: 'GTQ', description: 'Guatemala Quetzal')
Currency.create(currency_code: 'GYD', description: 'Guyana Dollar')
Currency.create(currency_code: 'HKD', description: 'Hong Kong Dollar')
Currency.create(currency_code: 'HNL', description: 'Honduras Lempira')
Currency.create(currency_code: 'HRK', description: 'Croatia Kuna')
Currency.create(currency_code: 'HTG', description: 'Haiti Gourde')
Currency.create(currency_code: 'HUF', description: 'Hungary Forint')
Currency.create(currency_code: 'IDR', description: 'Indonesia Rupiah')
Currency.create(currency_code: 'ILS', description: 'Israel Shekel')
Currency.create(currency_code: 'IMP', description: 'Isle of Man Pound')
Currency.create(currency_code: 'INR', description: 'India Rupee')
Currency.create(currency_code: 'IQD', description: 'Iraq Dinar')
Currency.create(currency_code: 'IRR', description: 'Iran Rial')
Currency.create(currency_code: 'ISK', description: 'Iceland Krona')
Currency.create(currency_code: 'JEP', description: 'Jersey Pound')
Currency.create(currency_code: 'JMD', description: 'Jamaica Dollar')
Currency.create(currency_code: 'JOD', description: 'Jordan Dinar')
Currency.create(currency_code: 'JPY', description: 'Japan Yen')
Currency.create(currency_code: 'KES', description: 'Kenya Shilling')
Currency.create(currency_code: 'KGS', description: 'Kyrgyzstan Som')
Currency.create(currency_code: 'KHR', description: 'Cambodia Riel')
Currency.create(currency_code: 'KMF', description: 'Comoros Franc')
Currency.create(currency_code: 'KPW', description: 'Korea (North) Won')
Currency.create(currency_code: 'KRW', description: 'Korea (South) Won')
Currency.create(currency_code: 'KWD', description: 'Kuwait Dinar')
Currency.create(currency_code: 'KYD', description: 'Cayman Islands Dollar')
Currency.create(currency_code: 'KZT', description: 'Kazakhstan Tenge')
Currency.create(currency_code: 'LAK', description: 'Laos Kip')
Currency.create(currency_code: 'LBP', description: 'Lebanon Pound')
Currency.create(currency_code: 'LKR', description: 'Sri Lanka Rupee')
Currency.create(currency_code: 'LRD', description: 'Liberia Dollar')
Currency.create(currency_code: 'LSL', description: 'Lesotho Loti')
Currency.create(currency_code: 'LYD', description: 'Libya Dinar')
Currency.create(currency_code: 'MAD', description: 'Morocco Dirham')
Currency.create(currency_code: 'MDL', description: 'Moldova Leu')
Currency.create(currency_code: 'MGA', description: 'Madagascar Ariary')
Currency.create(currency_code: 'MKD', description: 'Macedonia Denar')
Currency.create(currency_code: 'MMK', description: 'Myanmar (Burma) Kyat')
Currency.create(currency_code: 'MNT', description: 'Mongolia Tughrik')
Currency.create(currency_code: 'MOP', description: 'Macau Pataca')
Currency.create(currency_code: 'MRO', description: 'Mauritania Ouguiya')
Currency.create(currency_code: 'MUR', description: 'Mauritius Rupee')
Currency.create(currency_code: 'MVR', description: 'Maldives (Maldive Islands) Rufiyaa')
Currency.create(currency_code: 'MWK', description: 'Malawi Kwacha')
Currency.create(currency_code: 'MXN', description: 'Mexico Peso')
Currency.create(currency_code: 'MYR', description: 'Malaysia Ringgit')
Currency.create(currency_code: 'MZN', description: 'Mozambique Metical')
Currency.create(currency_code: 'NAD', description: 'Namibia Dollar')
Currency.create(currency_code: 'NGN', description: 'Nigeria Naira')
Currency.create(currency_code: 'NIO', description: 'Nicaragua Cordoba')
Currency.create(currency_code: 'NOK', description: 'Norway Krone')
Currency.create(currency_code: 'NPR', description: 'Nepal Rupee')
Currency.create(currency_code: 'NZD', description: 'New Zealand Dollar')
Currency.create(currency_code: 'OMR', description: 'Oman Rial')
Currency.create(currency_code: 'PAB', description: 'Panama Balboa')
Currency.create(currency_code: 'PEN', description: 'Peru Nuevo Sol')
Currency.create(currency_code: 'PGK', description: 'Papua New Guinea Kina')
Currency.create(currency_code: 'PHP', description: 'Philippines Peso')
Currency.create(currency_code: 'PKR', description: 'Pakistan Rupee')
Currency.create(currency_code: 'PLN', description: 'Poland Zloty')
Currency.create(currency_code: 'PYG', description: 'Paraguay Guarani')
Currency.create(currency_code: 'QAR', description: 'Qatar Riyal')
Currency.create(currency_code: 'RON', description: 'Romania New Leu')
Currency.create(currency_code: 'RSD', description: 'Serbia Dinar')
Currency.create(currency_code: 'RUB', description: 'Russia Ruble')
Currency.create(currency_code: 'RWF', description: 'Rwanda Franc')
Currency.create(currency_code: 'SAR', description: 'Saudi Arabia Riyal')
Currency.create(currency_code: 'SBD', description: 'Solomon Islands Dollar')
Currency.create(currency_code: 'SCR', description: 'Seychelles Rupee')
Currency.create(currency_code: 'SDG', description: 'Sudan Pound')
Currency.create(currency_code: 'SEK', description: 'Sweden Krona')
Currency.create(currency_code: 'SGD', description: 'Singapore Dollar')
Currency.create(currency_code: 'SHP', description: 'Saint Helena Pound')
Currency.create(currency_code: 'SLL', description: 'Sierra Leone Leone')
Currency.create(currency_code: 'SOS', description: 'Somalia Shilling')
Currency.create(currency_code: 'SPL', description: 'Seborga Luigino')
Currency.create(currency_code: 'SRD', description: 'Suriname Dollar')
Currency.create(currency_code: 'STD', description: 'São Tomé and Príncipe Dobra')
Currency.create(currency_code: 'SVC', description: 'El Salvador Colon')
Currency.create(currency_code: 'SYP', description: 'Syria Pound')
Currency.create(currency_code: 'SZL', description: 'Swaziland Lilangeni')
Currency.create(currency_code: 'THB', description: 'Thailand Baht')
Currency.create(currency_code: 'TJS', description: 'Tajikistan Somoni')
Currency.create(currency_code: 'TMT', description: 'Turkmenistan Manat')
Currency.create(currency_code: 'TND', description: 'Tunisia Dinar')
Currency.create(currency_code: 'TOP', description: 'Tonga Pa anga')
Currency.create(currency_code: 'TRY', description: 'Turkey Lira')
Currency.create(currency_code: 'TTD', description: 'Trinidad and Tobago Dollar')
Currency.create(currency_code: 'TVD', description: 'Tuvalu Dollar')
Currency.create(currency_code: 'TWD', description: 'Taiwan New Dollar')
Currency.create(currency_code: 'TZS', description: 'Tanzania Shilling')
Currency.create(currency_code: 'UAH', description: 'Ukraine Hryvnia')
Currency.create(currency_code: 'UGX', description: 'Uganda Shilling')
Currency.create(currency_code: 'USD', description: 'United States Dollar')
Currency.create(currency_code: 'UYU', description: 'Uruguay Peso')
Currency.create(currency_code: 'UZS', description: 'Uzbekistan Som')
Currency.create(currency_code: 'VEF', description: 'Venezuela Bolivar')
Currency.create(currency_code: 'VND', description: 'Viet Nam Dong')
Currency.create(currency_code: 'VUV', description: 'Vanuatu Vatu')
Currency.create(currency_code: 'WST', description: 'Samoa Tala')
Currency.create(currency_code: 'XAF', description: 'Communauté Financière Africaine (BEAC) CFA Franc BEAC')
Currency.create(currency_code: 'XCD', description: 'East Caribbean Dollar')
Currency.create(currency_code: 'XDR', description: 'International Monetary Fund (IMF) Special Drawing Rights')
Currency.create(currency_code: 'XOF', description: 'Communauté Financière Africaine (BCEAO) Franc')
Currency.create(currency_code: 'XPF', description: 'Comptoirs Français du Pacifique (CFP) Franc')
Currency.create(currency_code: 'YER', description: 'Yemen Rial')
Currency.create(currency_code: 'ZAR', description: 'South Africa Rand')
Currency.create(currency_code: 'ZMW', description: 'Zambia Kwacha')
Currency.create(currency_code: 'ZWD', description: 'Zimbabwe Dollar')

#instruction Text
TextInstruction.create(key: 'instruction.dashboard', value: 'The Dashboard provides the user with a fron end user insterface for accessing all of the application.<br/><br/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mattis sapien in velit rutrum, ac ornare augue pretium. Pellentesque et mi porta, vestibulum dolor at, dapibus felis. Sed feugiat lectus id leo faucibus, in dignissim tortor consequat. Cras venenatis, orci auctor condimentum dignissim, lorem quam pulvinar nisl, a imperdiet nulla neque eu eros. Mauris a justo ullamcorper, vehicula lectus quis, congue urna. Quisque in mi purus. Curabitur eget sem ut eros rhoncus euismod. Suspendisse id aliquam libero. Suspendisse pharetra eu lectus at ornare. Sed ac fringilla tortor. Aliquam in nunc ut eros tristique vulputate. Nulla molestie mattis purus vel faucibus. Nullam laoreet erat eu aliquam interdum.')

#Translations (English)
Translation.create(locale: 'en', key: 'login.username', value: 'Username')
Translation.create(locale: 'en', key: 'login.password', value: 'Password')
Translation.create(locale: 'en', key: 'login.header', value: 'Sign in')
Translation.create(locale: 'en', key: 'login.login', value: 'Login')
Translation.create(locale: 'en', key: 'login.forgotpassword', value: 'Forgot password?')
Translation.create(locale: 'en', key: 'login.rememberme', value: 'Remember me?')
Translation.create(locale: 'en', key: 'button.save', value: 'Save')
Translation.create(locale: 'en', key: 'button.edit', value: 'Edit')
Translation.create(locale: 'en', key: 'button.view', value: 'View')
Translation.create(locale: 'en', key: 'button.delete', value: 'Delete')
Translation.create(locale: 'en', key: 'button.search', value: 'Search')
Translation.create(locale: 'en', key: 'button.return_to_search', value: 'Return to Search')
Translation.create(locale: 'es', key: 'button.cancel', value: 'Cancel')
Translation.create(locale: 'en', key: 'button.add_pay_component', value: 'Add Pay Component')
Translation.create(locale: 'en', key: 'button.add_employee', value: 'Add Employee')
Translation.create(locale: 'en', key: 'button.add_emergency_contact', value: 'Add Emergency Contact')
Translation.create(locale: 'en', key: 'button.add_supervisor', value: 'Add Supervisor')
Translation.create(locale: 'en', key: 'button.add_dependent', value: 'Add Dependent')
Translation.create(locale: 'en', key: 'button.add_location', value: 'Add Location')
Translation.create(locale: 'en', key: 'button.add_user', value: 'Add User')
Translation.create(locale: 'en', key: 'button.upload', value: 'Upload')
Translation.create(locale: 'en', key: 'button.upload_new_photo', value: 'Upload New Photo')
Translation.create(locale: 'en', key: 'button.terminate_employee', value: 'Terminate Employee')
Translation.create(locale: 'en', key: 'button.reactivate_employee', value: 'Reactivate Employee')
Translation.create(locale: 'en', key: 'button.view_job_history', value: 'View Job History')
Translation.create(locale: 'en', key: 'button.provide_user_details', value: 'Provide User Details?')
Translation.create(locale: 'en', key: 'button.change_password', value: 'Change Password?')
Translation.create(locale: 'en', key: 'page_header.departments', value: 'Departments')
Translation.create(locale: 'en', key: 'page_header.locations', value: 'Locations')
Translation.create(locale: 'en', key: 'page_header.search_results', value: 'Search Results')
Translation.create(locale: 'en', key: 'menu.dashboard', value: 'Dashboard')
Translation.create(locale: 'en', key: 'menu.people', value: 'People')
Translation.create(locale: 'en', key: 'menu.administration', value: 'Administration')
Translation.create(locale: 'en', key: 'menu.configuration', value: 'Configuration')
Translation.create(locale: 'en', key: 'menu.my_profile', value: 'My Profile')
Translation.create(locale: 'en', key: 'menu.logout', value: 'Logout')

#Translations (Spanish)
Translation.create(locale: 'es', key: 'login.username', value: 'Nombre de Usuario')
Translation.create(locale: 'es', key: 'login.password', value: 'Clave')
Translation.create(locale: 'es', key: 'login.header', value: 'Registrarse')
Translation.create(locale: 'es', key: 'login.login', value: 'Iniciar Sesión')
Translation.create(locale: 'es', key: 'login.forgotpassword', value: '¿Se te olvidó tu contraseña?')
Translation.create(locale: 'es', key: 'login.rememberme', value: '¿Acuérdate de mí?')
Translation.create(locale: 'es', key: 'button.save', value: 'Guardar')
Translation.create(locale: 'es', key: 'button.edit', value: 'Editar')
Translation.create(locale: 'es', key: 'button.view', value: 'Ver')
Translation.create(locale: 'es', key: 'button.delete', value: 'Borrar')
Translation.create(locale: 'es', key: 'button.search', value: 'Buscar')
Translation.create(locale: 'es', key: 'button.return_to_search', value: 'Volver a la Búsqueda')
Translation.create(locale: 'es', key: 'button.cancel', value: 'Canclear')
Translation.create(locale: 'es', key: 'button.add_pay_component', value: 'Añadir componentes de Pago')
Translation.create(locale: 'es', key: 'button.add_employee', value: 'Añadir Empleado')
Translation.create(locale: 'es', key: 'button.add_emergency_contact', value: 'Añadir contactos de emergencia')
Translation.create(locale: 'es', key: 'button.add_supervisor', value: 'Añadir el Supervisor')
Translation.create(locale: 'es', key: 'button.add_dependent', value: 'Añadir Dependientes')
Translation.create(locale: 'es', key: 'button.add_location', value: 'Agregar Direccion')
Translation.create(locale: 'es', key: 'button.add_user', value: 'Agregar Usuario')
Translation.create(locale: 'es', key: 'button.upload', value: 'Subir')
Translation.create(locale: 'es', key: 'button.upload_new_photo', value: 'Sube nueva foto')
Translation.create(locale: 'es', key: 'button.terminate_employee', value: 'Terminar Empleado')
Translation.create(locale: 'es', key: 'button.reactivate_employee', value: 'Reactivar Empleado')
Translation.create(locale: 'es', key: 'button.view_job_history', value: 'Ver trabajo Historia')
Translation.create(locale: 'es', key: 'button.provide_user_details', value: '¿Proporcione Detalles de Usuario?')
Translation.create(locale: 'es', key: 'button.change_password', value: '¿Cambiar la Contraseña?')
Translation.create(locale: 'es', key: 'page_header.departments', value: 'Departamentos')
Translation.create(locale: 'es', key: 'page_header.locations', value: 'Ubicaciones')
Translation.create(locale: 'es', key: 'page_header.search_results', value: 'Resultados de la búsqueda')
Translation.create(locale: 'es', key: 'menu.dashboard', value: 'Tablero')
Translation.create(locale: 'es', key: 'menu.people', value: 'Gente')
Translation.create(locale: 'es', key: 'menu.administration', value: 'Administración')
Translation.create(locale: 'es', key: 'menu.configuration', value: 'Configuración')
Translation.create(locale: 'es', key: 'menu.logout', value: 'Cerrar Sesión')
Translation.create(locale: 'es', key: 'menu.my_profile', value: 'Mi Perfil')