# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

#Users (for demo)
User.create(username: 'Administrator', password: 'password', password_confirmation: 'password', role: 'admin', locale: 'en')
User.create(username: 'Employee', password: 'password', password_confirmation: 'password', role: 'employee', locale: 'en')
User.create(username: 'Manager', password: 'password', password_confirmation: 'password', role: 'manager', locale: 'en')

#Languages
Language.create(language_description: 'English')
Language.create(language_description: 'Spanish')
Language.create(language_description: 'French')
Language.create(language_description: 'Italian')
Language.create(language_description: 'Mandarin')
Language.create(language_description: 'Hindi')
Language.create(language_description: 'Arabic')
Language.create(language_description: 'Portuguese')
Language.create(language_description: 'Bengali')
Language.create(language_description: 'Russian')
Language.create(language_description: 'Japanese')
Language.create(language_description: 'German')
Language.create(language_description: 'Vietnamese')
Language.create(language_description: 'Dutch')
Language.create(language_description: 'Polish')
Language.create(language_description: 'Swedish')
Language.create(language_description: 'Danish')
Language.create(language_description: 'Norwegian')
Language.create(language_description: 'Turkish')
Language.create(language_description: 'English')

#Countries
Country.create(country_code: 'US', description: 'United States of America')
Country.create(country_code: 'CA', description: 'Canada')

#States
# USA
State.create(country_id: '1', state_code: 'AL', description: 'Alabama')
State.create(country_id: '1', state_code: 'AZ', description: 'Arizona')
State.create(country_id: '1', state_code: 'AR', description: 'Arkansas')
State.create(country_id: '1', state_code: 'CA', description: 'California')
State.create(country_id: '1', state_code: 'CO', description: 'Colorado')
State.create(country_id: '1', state_code: 'CT', description: 'Connecticut')
State.create(country_id: '1', state_code: 'DE', description: 'Deleware')
State.create(country_id: '1', state_code: 'FL', description: 'Florida')
State.create(country_id: '1', state_code: 'GA', description: 'Georgia')
State.create(country_id: '1', state_code: 'HI', description: 'Hawaii')
State.create(country_id: '1', state_code: 'ID', description: 'Idaho')
State.create(country_id: '1', state_code: 'IL', description: 'Illinois')
State.create(country_id: '1', state_code: 'IN', description: 'Indiana')
State.create(country_id: '1', state_code: 'IA', description: 'Iowa')
State.create(country_id: '1', state_code: 'KS', description: 'Kansas')
State.create(country_id: '1', state_code: 'KY', description: 'Kentucky')
State.create(country_id: '1', state_code: 'LA', description: 'Louisiana')
State.create(country_id: '1', state_code: 'ME', description: 'Maine')
State.create(country_id: '1', state_code: 'MD', description: 'Maryland')
State.create(country_id: '1', state_code: 'MA', description: 'Massachussetts')
State.create(country_id: '1', state_code: 'MI', description: 'Michigan')
State.create(country_id: '1', state_code: 'MN', description: 'Minnesota')
State.create(country_id: '1', state_code: 'MS', description: 'Mississippi')
State.create(country_id: '1', state_code: 'MO', description: 'Missouri')
State.create(country_id: '1', state_code: 'MT', description: 'ontana')
State.create(country_id: '1', state_code: 'NE', description: 'Nebraska')
State.create(country_id: '1', state_code: 'NV', description: 'Nevada')
State.create(country_id: '1', state_code: 'NH', description: 'New Hampshire')
State.create(country_id: '1', state_code: 'NJ', description: 'New Jersey')
State.create(country_id: '1', state_code: 'NM', description: 'New Mexico')
State.create(country_id: '1', state_code: 'NY', description: 'New York')
State.create(country_id: '1', state_code: 'NC', description: 'North Carolina')
State.create(country_id: '1', state_code: 'ND', description: 'North Dakota')
State.create(country_id: '1', state_code: 'OH', description: 'Ohio')
State.create(country_id: '1', state_code: 'OK', description: 'Oklahoma')
State.create(country_id: '1', state_code: 'OR', description: 'Oregon')
State.create(country_id: '1', state_code: 'PA', description: 'Pennsylvania')
State.create(country_id: '1', state_code: 'RI', description: 'Rhode Island')
State.create(country_id: '1', state_code: 'SC', description: 'South Carolina')
State.create(country_id: '1', state_code: 'SD', description: 'South Dakota')
State.create(country_id: '1', state_code: 'TN', description: 'Tennessee')
State.create(country_id: '1', state_code: 'TX', description: 'Texas')
State.create(country_id: '1', state_code: 'UT', description: 'Utah')
State.create(country_id: '1', state_code: 'VT', description: 'Vermonth')
State.create(country_id: '1', state_code: 'VA', description: 'Virginia')
State.create(country_id: '1', state_code: 'WA', description: 'Washington')
State.create(country_id: '1', state_code: 'WV', description: 'West Virginia')
State.create(country_id: '1', state_code: 'WI', description: 'Wisconsin')
State.create(country_id: '1', state_code: 'WY', description: 'Wyoming')

#States
#Canada
State.create(country_id: '2', state_code: 'AB', description: 'Alberta')
State.create(country_id: '2', state_code: 'BC', description: 'British Columbia')
State.create(country_id: '2', state_code: 'MB', description: 'Manitoba')
State.create(country_id: '2', state_code: 'NB', description: 'New Brunswick')
State.create(country_id: '2', state_code: 'NL', description: 'Newfoundland and Labrador')
State.create(country_id: '2', state_code: 'NS', description: 'Nova Scotia')
State.create(country_id: '2', state_code: 'ON', description: 'Ontario')
State.create(country_id: '2', state_code: 'PE', description: 'Prince Edward Island')
State.create(country_id: '2', state_code: 'QC', description: 'Quebec')
State.create(country_id: '2', state_code: 'SK', description: 'Saskatchewan')

#System Languages/Locales
SystemLanguage.create(language_code: 'af', language_description: 'Afrikaans')
SystemLanguage.create(language_code: 'ar', language_description: 'Arabic')
SystemLanguage.create(language_code: 'az', language_description: 'Azeri')
SystemLanguage.create(language_code: 'bg', language_description: 'Bulgarian')
SystemLanguage.create(language_code: 'bn', language_description: 'Bengali')
SystemLanguage.create(language_code: 'bs', language_description: 'Bosnian')
SystemLanguage.create(language_code: 'ca', language_description: 'Catalan')
SystemLanguage.create(language_code: 'cs', language_description: 'Czech')
SystemLanguage.create(language_code: 'cy', language_description: 'Welch')
SystemLanguage.create(language_code: 'da', language_description: 'Danish')
SystemLanguage.create(language_code: 'de', language_description: 'German')
SystemLanguage.create(language_code: 'de-AT', language_description: 'German (Austria)')
SystemLanguage.create(language_code: 'de-CH', language_description: 'German (Switzerland)')
SystemLanguage.create(language_code: 'el', language_description: 'Greek')
SystemLanguage.create(language_code: 'en', language_description: 'English')
SystemLanguage.create(language_code: 'en-AU', language_description: 'English (Austalia)')
SystemLanguage.create(language_code: 'en-CA', language_description: 'English (Canada)')
SystemLanguage.create(language_code: 'en-GB', language_description: 'English (Great Britain)')
SystemLanguage.create(language_code: 'en-IE', language_description: 'English (Ireland)')
SystemLanguage.create(language_code: 'en-IN', language_description: 'English (India)')
SystemLanguage.create(language_code: 'en-NZ', language_description: 'English (New Zealand)')
SystemLanguage.create(language_code: 'en-US', language_description: 'English (US)')
SystemLanguage.create(language_code: 'en-ZA', language_description: 'English (South Africa)')
SystemLanguage.create(language_code: 'eo', language_description: 'Esperanto')
SystemLanguage.create(language_code: 'es', language_description: 'Spanish')
SystemLanguage.create(language_code: 'es-419', language_description: 'Spanish (Latin America)')
SystemLanguage.create(language_code: 'es-AR', language_description: 'Spanish (Argentina)')
SystemLanguage.create(language_code: 'es-CL', language_description: 'Spanish (Chile)')
SystemLanguage.create(language_code: 'es-CO', language_description: 'Spanish (Columbia)')
SystemLanguage.create(language_code: 'es-CR', language_description: 'Spanish (Costa Rica)')
SystemLanguage.create(language_code: 'es-EC', language_description: 'Spanish (Ecuator)')
SystemLanguage.create(language_code: 'es-MX', language_description: 'Spanish (Mexico)')
SystemLanguage.create(language_code: 'es-PA', language_description: 'Spanish (Panama)')
SystemLanguage.create(language_code: 'es-PE', language_description: 'Spanish (Peru)')
SystemLanguage.create(language_code: 'es-US', language_description: 'Spanish (United States)')
SystemLanguage.create(language_code: 'es-VE', language_description: 'Spanish (Venezuela)')
SystemLanguage.create(language_code: 'et', language_description: 'Estonian')
SystemLanguage.create(language_code: 'eu', language_description: 'Basque')
SystemLanguage.create(language_code: 'fa', language_description: 'Farsi')
SystemLanguage.create(language_code: 'fi', language_description: 'Finnish')
SystemLanguage.create(language_code: 'fr', language_description: 'French')
SystemLanguage.create(language_code: 'fr-CA', language_description: 'French (Canada)')
SystemLanguage.create(language_code: 'fr-CH', language_description: 'French (Switzerland)')
SystemLanguage.create(language_code: 'gl', language_description: 'Galician')
SystemLanguage.create(language_code: 'he', language_description: 'Hebrew')
SystemLanguage.create(language_code: 'hi', language_description: 'Hindi')
SystemLanguage.create(language_code: 'hi-IN', language_description: 'Hindi (India')
SystemLanguage.create(language_code: 'hr', language_description: 'Croatian')
SystemLanguage.create(language_code: 'hu', language_description: 'Hungarian')
SystemLanguage.create(language_code: 'id', language_description: 'Indonesian')
SystemLanguage.create(language_code: 'is', language_description: 'Icelandic')
SystemLanguage.create(language_code: 'it', language_description: 'Italian')
SystemLanguage.create(language_code: 'it-CH', language_description: 'Italian (Switzerland)')
SystemLanguage.create(language_code: 'ja', language_description: 'Japanese')
SystemLanguage.create(language_code: 'km', language_description: 'Khmer')
SystemLanguage.create(language_code: 'kn', language_description: 'Kannada')
SystemLanguage.create(language_code: 'ko', language_description: 'Korean')
SystemLanguage.create(language_code: 'lo', language_description: 'Lao')
SystemLanguage.create(language_code: 'lt', language_description: 'Lithuanian')
SystemLanguage.create(language_code: 'lv', language_description: 'Latvian')
SystemLanguage.create(language_code: 'mk', language_description: 'Macedonian')
SystemLanguage.create(language_code: 'mn', language_description: 'Mongolian')
SystemLanguage.create(language_code: 'mr-IN', language_description: 'Marathi (India)')
SystemLanguage.create(language_code: 'ms', language_description: 'Malay')
SystemLanguage.create(language_code: 'nb', language_description: 'Norwegian')
SystemLanguage.create(language_code: 'ne', language_description: 'Nepali')
SystemLanguage.create(language_code: 'nl', language_description: 'Dutch')
SystemLanguage.create(language_code: 'nn', language_description: 'Norwegian')
SystemLanguage.create(language_code: 'or', language_description: 'Oryia')
SystemLanguage.create(language_code: 'pl', language_description: 'Polish')
SystemLanguage.create(language_code: 'pt', language_description: 'Portuguese (Portugal)')
SystemLanguage.create(language_code: 'pt-BR', language_description: 'Portuguese (Brazil)')
SystemLanguage.create(language_code: 'rm', language_description: 'Raeto (Romance)')
SystemLanguage.create(language_code: 'ro', language_description: 'Romanian')
SystemLanguage.create(language_code: 'ru', language_description: 'Russian')
SystemLanguage.create(language_code: 'sk', language_description: 'Slovak')
SystemLanguage.create(language_code: 'sl', language_description: 'Slovanian')
SystemLanguage.create(language_code: 'sr', language_description: 'Serbian')
SystemLanguage.create(language_code: 'sv', language_description: 'Swedish')
SystemLanguage.create(language_code: 'sw', language_description: 'Swahili')
SystemLanguage.create(language_code: 'ta', language_description: 'Tamil')
SystemLanguage.create(language_code: 'th', language_description: 'Thai')
SystemLanguage.create(language_code: 'tl', language_description: 'Tagalog')
SystemLanguage.create(language_code: 'tr', language_description: 'Turkish')
SystemLanguage.create(language_code: 'tt', language_description: 'Tatar')
SystemLanguage.create(language_code: 'uk', language_description: 'Ukranian')
SystemLanguage.create(language_code: 'ug', language_description: 'Uighur')
SystemLanguage.create(language_code: 'ur', language_description: 'Urdu')
SystemLanguage.create(language_code: 'uz', language_description: 'Uzbek')
SystemLanguage.create(language_code: 'vi', language_description: 'Vietnamese')
SystemLanguage.create(language_code: 'wo', language_description: 'Wolof')
SystemLanguage.create(language_code: 'zh-CN', language_description: 'Chinese (Simplified)')
SystemLanguage.create(language_code: 'zh-HK', language_description: 'Chinese (Hong Kong)')
SystemLanguage.create(language_code: 'zh-TW', language_description: 'Chinese (Traditional)')
SystemLanguage.create(language_code: 'zh-YUE', language_description: 'Chinese (Yue)')

#Currency Codes
Currency.create(currency_code: 'AED', description: 'United Arab Emirates Dirham')
Currency.create(currency_code: 'AFN', description: 'Afghanistan Afghani')
Currency.create(currency_code: 'ALL', description: 'Albania Lek')
Currency.create(currency_code: 'AMD', description: 'Armenia Dram')
Currency.create(currency_code: 'ANG', description: 'Netherlands Antilles Guilder')
Currency.create(currency_code: 'AOA', description: 'Angola Kwanza')
Currency.create(currency_code: 'ARS', description: 'Argentina Peso')
Currency.create(currency_code: 'AUD', description: 'Australia Dollar')
Currency.create(currency_code: 'AWG', description: 'Aruba Guilder')
Currency.create(currency_code: 'AZN', description: 'Azerbaijan New Manat')
Currency.create(currency_code: 'BAM', description: 'Bosnia and Herzegovina Convertible Marka')
Currency.create(currency_code: 'BBD', description: 'Barbados Dollar')
Currency.create(currency_code: 'BDT', description: 'Bangladesh Taka')
Currency.create(currency_code: 'BGN', description: 'Bulgaria Lev')
Currency.create(currency_code: 'BHD', description: 'Bahrain Dinar')
Currency.create(currency_code: 'BIF', description: 'Burundi Franc')
Currency.create(currency_code: 'BMD', description: 'Bermuda Dollar')
Currency.create(currency_code: 'BND', description: 'Brunei Darussalam Dollar')
Currency.create(currency_code: 'BOB', description: 'Bolivia Boliviano')
Currency.create(currency_code: 'BRL', description: 'Brazil Real')
Currency.create(currency_code: 'BSD', description: 'Bahamas Dollar')
Currency.create(currency_code: 'BTN', description: 'Bhutan Ngultrum')
Currency.create(currency_code: 'BWP', description: 'Botswana Pula')
Currency.create(currency_code: 'BYR', description: 'Belarus Ruble')
Currency.create(currency_code: 'BZD', description: 'Belize Dollar')
Currency.create(currency_code: 'CAD', description: 'Canada Dollar')
Currency.create(currency_code: 'CDF', description: 'Congo/Kinshasa Franc')
Currency.create(currency_code: 'CHF', description: 'Switzerland Franc')
Currency.create(currency_code: 'CLP', description: 'Chile Peso')
Currency.create(currency_code: 'CNY', description: 'China Yuan Renminbi')
Currency.create(currency_code: 'COP', description: 'Colombia Peso')
Currency.create(currency_code: 'CRC', description: 'Costa Rica Colon')
Currency.create(currency_code: 'CUC', description: 'Cuba Convertible Peso')
Currency.create(currency_code: 'CUP', description: 'Cuba Peso')
Currency.create(currency_code: 'CVE', description: 'Cape Verde Escudo')
Currency.create(currency_code: 'CZK', description: 'Czech Republic Koruna')
Currency.create(currency_code: 'DJF', description: 'Djibouti Franc')
Currency.create(currency_code: 'DKK', description: 'Denmark Krone')
Currency.create(currency_code: 'DOP', description: 'Dominican Republic Peso')
Currency.create(currency_code: 'DZD', description: 'Algeria Dinar')
Currency.create(currency_code: 'EGP', description: 'Egypt Pound')
Currency.create(currency_code: 'ERN', description: 'Eritrea Nakfa')
Currency.create(currency_code: 'ETB', description: 'Ethiopia Birr')
Currency.create(currency_code: 'EUR', description: 'Euro')
Currency.create(currency_code: 'FJD', description: 'Fiji Dollar')
Currency.create(currency_code: 'FKP', description: 'Falkland Islands (Malvinas) Pound')
Currency.create(currency_code: 'GBP', description: 'United Kingdom Pound')
Currency.create(currency_code: 'GEL', description: 'Georgia Lari')
Currency.create(currency_code: 'GGP', description: 'Guernsey Pound')
Currency.create(currency_code: 'GHS', description: 'Ghana Cedi')
Currency.create(currency_code: 'GIP', description: 'Gibraltar Pound')
Currency.create(currency_code: 'GMD', description: 'Gambia Dalasi')
Currency.create(currency_code: 'GNF', description: 'Guinea Franc')
Currency.create(currency_code: 'GTQ', description: 'Guatemala Quetzal')
Currency.create(currency_code: 'GYD', description: 'Guyana Dollar')
Currency.create(currency_code: 'HKD', description: 'Hong Kong Dollar')
Currency.create(currency_code: 'HNL', description: 'Honduras Lempira')
Currency.create(currency_code: 'HRK', description: 'Croatia Kuna')
Currency.create(currency_code: 'HTG', description: 'Haiti Gourde')
Currency.create(currency_code: 'HUF', description: 'Hungary Forint')
Currency.create(currency_code: 'IDR', description: 'Indonesia Rupiah')
Currency.create(currency_code: 'ILS', description: 'Israel Shekel')
Currency.create(currency_code: 'IMP', description: 'Isle of Man Pound')
Currency.create(currency_code: 'INR', description: 'India Rupee')
Currency.create(currency_code: 'IQD', description: 'Iraq Dinar')
Currency.create(currency_code: 'IRR', description: 'Iran Rial')
Currency.create(currency_code: 'ISK', description: 'Iceland Krona')
Currency.create(currency_code: 'JEP', description: 'Jersey Pound')
Currency.create(currency_code: 'JMD', description: 'Jamaica Dollar')
Currency.create(currency_code: 'JOD', description: 'Jordan Dinar')
Currency.create(currency_code: 'JPY', description: 'Japan Yen')
Currency.create(currency_code: 'KES', description: 'Kenya Shilling')
Currency.create(currency_code: 'KGS', description: 'Kyrgyzstan Som')
Currency.create(currency_code: 'KHR', description: 'Cambodia Riel')
Currency.create(currency_code: 'KMF', description: 'Comoros Franc')
Currency.create(currency_code: 'KPW', description: 'Korea (North) Won')
Currency.create(currency_code: 'KRW', description: 'Korea (South) Won')
Currency.create(currency_code: 'KWD', description: 'Kuwait Dinar')
Currency.create(currency_code: 'KYD', description: 'Cayman Islands Dollar')
Currency.create(currency_code: 'KZT', description: 'Kazakhstan Tenge')
Currency.create(currency_code: 'LAK', description: 'Laos Kip')
Currency.create(currency_code: 'LBP', description: 'Lebanon Pound')
Currency.create(currency_code: 'LKR', description: 'Sri Lanka Rupee')
Currency.create(currency_code: 'LRD', description: 'Liberia Dollar')
Currency.create(currency_code: 'LSL', description: 'Lesotho Loti')
Currency.create(currency_code: 'LYD', description: 'Libya Dinar')
Currency.create(currency_code: 'MAD', description: 'Morocco Dirham')
Currency.create(currency_code: 'MDL', description: 'Moldova Leu')
Currency.create(currency_code: 'MGA', description: 'Madagascar Ariary')
Currency.create(currency_code: 'MKD', description: 'Macedonia Denar')
Currency.create(currency_code: 'MMK', description: 'Myanmar (Burma) Kyat')
Currency.create(currency_code: 'MNT', description: 'Mongolia Tughrik')
Currency.create(currency_code: 'MOP', description: 'Macau Pataca')
Currency.create(currency_code: 'MRO', description: 'Mauritania Ouguiya')
Currency.create(currency_code: 'MUR', description: 'Mauritius Rupee')
Currency.create(currency_code: 'MVR', description: 'Maldives (Maldive Islands) Rufiyaa')
Currency.create(currency_code: 'MWK', description: 'Malawi Kwacha')
Currency.create(currency_code: 'MXN', description: 'Mexico Peso')
Currency.create(currency_code: 'MYR', description: 'Malaysia Ringgit')
Currency.create(currency_code: 'MZN', description: 'Mozambique Metical')
Currency.create(currency_code: 'NAD', description: 'Namibia Dollar')
Currency.create(currency_code: 'NGN', description: 'Nigeria Naira')
Currency.create(currency_code: 'NIO', description: 'Nicaragua Cordoba')
Currency.create(currency_code: 'NOK', description: 'Norway Krone')
Currency.create(currency_code: 'NPR', description: 'Nepal Rupee')
Currency.create(currency_code: 'NZD', description: 'New Zealand Dollar')
Currency.create(currency_code: 'OMR', description: 'Oman Rial')
Currency.create(currency_code: 'PAB', description: 'Panama Balboa')
Currency.create(currency_code: 'PEN', description: 'Peru Nuevo Sol')
Currency.create(currency_code: 'PGK', description: 'Papua New Guinea Kina')
Currency.create(currency_code: 'PHP', description: 'Philippines Peso')
Currency.create(currency_code: 'PKR', description: 'Pakistan Rupee')
Currency.create(currency_code: 'PLN', description: 'Poland Zloty')
Currency.create(currency_code: 'PYG', description: 'Paraguay Guarani')
Currency.create(currency_code: 'QAR', description: 'Qatar Riyal')
Currency.create(currency_code: 'RON', description: 'Romania New Leu')
Currency.create(currency_code: 'RSD', description: 'Serbia Dinar')
Currency.create(currency_code: 'RUB', description: 'Russia Ruble')
Currency.create(currency_code: 'RWF', description: 'Rwanda Franc')
Currency.create(currency_code: 'SAR', description: 'Saudi Arabia Riyal')
Currency.create(currency_code: 'SBD', description: 'Solomon Islands Dollar')
Currency.create(currency_code: 'SCR', description: 'Seychelles Rupee')
Currency.create(currency_code: 'SDG', description: 'Sudan Pound')
Currency.create(currency_code: 'SEK', description: 'Sweden Krona')
Currency.create(currency_code: 'SGD', description: 'Singapore Dollar')
Currency.create(currency_code: 'SHP', description: 'Saint Helena Pound')
Currency.create(currency_code: 'SLL', description: 'Sierra Leone Leone')
Currency.create(currency_code: 'SOS', description: 'Somalia Shilling')
Currency.create(currency_code: 'SPL', description: 'Seborga Luigino')
Currency.create(currency_code: 'SRD', description: 'Suriname Dollar')
Currency.create(currency_code: 'STD', description: 'São Tomé and Príncipe Dobra')
Currency.create(currency_code: 'SVC', description: 'El Salvador Colon')
Currency.create(currency_code: 'SYP', description: 'Syria Pound')
Currency.create(currency_code: 'SZL', description: 'Swaziland Lilangeni')
Currency.create(currency_code: 'THB', description: 'Thailand Baht')
Currency.create(currency_code: 'TJS', description: 'Tajikistan Somoni')
Currency.create(currency_code: 'TMT', description: 'Turkmenistan Manat')
Currency.create(currency_code: 'TND', description: 'Tunisia Dinar')
Currency.create(currency_code: 'TOP', description: 'Tonga Pa anga')
Currency.create(currency_code: 'TRY', description: 'Turkey Lira')
Currency.create(currency_code: 'TTD', description: 'Trinidad and Tobago Dollar')
Currency.create(currency_code: 'TVD', description: 'Tuvalu Dollar')
Currency.create(currency_code: 'TWD', description: 'Taiwan New Dollar')
Currency.create(currency_code: 'TZS', description: 'Tanzania Shilling')
Currency.create(currency_code: 'UAH', description: 'Ukraine Hryvnia')
Currency.create(currency_code: 'UGX', description: 'Uganda Shilling')
Currency.create(currency_code: 'USD', description: 'United States Dollar')
Currency.create(currency_code: 'UYU', description: 'Uruguay Peso')
Currency.create(currency_code: 'UZS', description: 'Uzbekistan Som')
Currency.create(currency_code: 'VEF', description: 'Venezuela Bolivar')
Currency.create(currency_code: 'VND', description: 'Viet Nam Dong')
Currency.create(currency_code: 'VUV', description: 'Vanuatu Vatu')
Currency.create(currency_code: 'WST', description: 'Samoa Tala')
Currency.create(currency_code: 'XAF', description: 'Communauté Financière Africaine (BEAC) CFA Franc BEAC')
Currency.create(currency_code: 'XCD', description: 'East Caribbean Dollar')
Currency.create(currency_code: 'XDR', description: 'International Monetary Fund (IMF) Special Drawing Rights')
Currency.create(currency_code: 'XOF', description: 'Communauté Financière Africaine (BCEAO) Franc')
Currency.create(currency_code: 'XPF', description: 'Comptoirs Français du Pacifique (CFP) Franc')
Currency.create(currency_code: 'YER', description: 'Yemen Rial')
Currency.create(currency_code: 'ZAR', description: 'South Africa Rand')
Currency.create(currency_code: 'ZMW', description: 'Zambia Kwacha')
Currency.create(currency_code: 'ZWD', description: 'Zimbabwe Dollar')

#Translations
Translation.create(locale: 'en', key: 'login.username', value: 'Username')
Translation.create(locale: 'en', key: 'login.password', value: 'Password')
Translation.create(locale: 'en', key: 'login.header', value: 'Sign in')
Translation.create(locale: 'en', key: 'login.login', value: 'Login')
Translation.create(locale: 'en', key: 'login.forgotpassword', value: 'Forgot password?')
Translation.create(locale: 'en', key: 'login.rememberme', value: 'Remember me?')
Translation.create(locale: 'en', key: 'button.save', value: 'Save')
Translation.create(locale: 'en', key: 'button.edit', value: 'Edit')
Translation.create(locale: 'en', key: 'button.delete', value: 'Delete')
Translation.create(locale: 'en', key: 'button.search', value: 'Search')
Translation.create(locale: 'en', key: 'button.return_to_search', value: 'Return to Search')
Translation.create(locale: 'en', key: 'button.add_pay_component', value: 'Add Pay Component')
Translation.create(locale: 'en', key: 'page_header.departments', value: 'Departments')
Translation.create(locale: 'en', key: 'page_header.locations', value: 'Locations')
Translation.create(locale: 'en', key: 'page_header.search_results', value: 'Search Results')